spring:
  profiles:
    active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: info
#server:
#  port: 11001
#spring:
#  application:
#    name: nacos-provider-usermanage
#  datasource:
#    url: jdbc:mysql://106.54.90.81:3306/Water?serverTimezone=UTC #jdbc:mysql://localhost:3306/water?serverTimezone=UTC
#    username: root
#    password: wanwan12
#    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver #org.gjt.mm.mysql.Driver
#    spring:
#      datasource:
#        hikari:
#          idle-timeout: 60000
#          maximum-pool-size: 30
#          minimum-idle: 10
#    hikari:
#      jdbc-url: jdbc:mysql://106.54.90.81:3306/Water?serverTimezone=UTC
#      username: root
#      password: wanwan12
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.232.1:8848 #配置Nacos地址
#  mybatis:
#    mapper-locations: classpath:mappers/mapperxml/*xml
#    type-aliases-package: com.mox.entity #指定Mybatis的实体目录